imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        siteName: %site.name%
    form:
        resources:
            - '::fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: JP\RaceBundle\Entity\User

    from_email:
        address: "%jp.mailer.from_address%"
        sender_name: "%jp.mailer.from_name%"

    registration:
        confirmation:
            enabled: true
            template: JPUserBundle:Emails:registration.txt.twig
        form:
            type: jp_user_registration

    resetting:
        form:
            type: jp_user_resetting
        email:
            template: JPUserBundle:Emails:resetPassword.txt.twig

    profile:
        form:
            type: jp_user_profile

    change_password:
        form:
            type: jp_user_change_password

jp_race:
    horse:
        best_age: [7,8]
        ok_age: [6,9]
    race:
        class_levels:
            1: [8,9,10]
            2: [4,5,6,7]
            3: [1,2,3]
        flat:
            min_distance: 1100
            max_distance: 3899
            ideal_weight:
                min: 8
                max: 10
        jump:
            min_distance: 3520
            max_distance: 7920
            ideal_weight:
                min: 9
                max: 11